### ISSUE TITLE
optimizer.load_state_dict(checkpoint['optimizer']) promble

### ISSUE THREAD

**Issue by suijua** [leijue222/Intra-and-Inter-Human-Relation-Network-for-MPEE#11]
Traceback (most recent call last):
  File "/home/wuxl/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/wuxl/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/wuxl/project/Intra-and-Inter-Human-Relation-Network-for-MPEE/tools/train.py", line 250, in <module>
    main()
  File "/home/wuxl/project/Intra-and-Inter-Human-Relation-Network-for-MPEE/tools/train.py", line 191, in main
    **_optimizer.load_state_dict(checkpoint['optimizer'])_**
  File "/home/wuxl/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/optim/optimizer.py", line 146, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

Hello! I have modified the model structure of **_Transformer Block_** , But there is something wrong for this, I want use your pretrained model to train, can you help me?

**Comment by leijue222** [comment]
1. First, I don't know what modifications you have made to the model structure.
2. Secondly, if you want to load the pre-trained model, you have to make sure that the key-value is corresponding. If you modify the original key or add a new key, the corresponding value cannot be loaded. In this case, the strict parameter should be set to False when loading. At this time, the missing parameters will not be loaded and no error will be reported.

**Comment by suijua** [comment]
> 1. First, I don't know what modifications you have made to the model structure.
> 2. Secondly, if you want to load the pre-trained model, you have to make sure that the key-value is corresponding. If you modify the original key or add a new key, the corresponding value cannot be loaded. In this case, the strict parameter should be set to False when loading. At this time, the missing parameters will not be loaded and no error will be reported.

ok, thanks for your reply and recommendation。
