### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Riverzxz** [leijue222/Intra-and-Inter-Human-Relation-Network-for-MPEE#2]
Thanks for your contribution. I got an error when I tested the model:
python tools/test.py --cfg experiments/OCHuman/interformer_ochuman_tph_192_p3_b8.yaml
Traceback (most recent call last):
  File "tools/test.py", line 171, in <module>
    main()
  File "tools/test.py", line 91, in main
    cfg, is_train=False
  File "/home/hjq/I2R-NET/tools/../lib/models/interformer.py", line 328, in get_pose_net
    model = InterFormer(cfg, **kwargs)
  File "/home/hjq/I2R-NET/tools/../lib/models/interformer.py", line 140, in __init__
    cfg, cfg.MODEL.SINGLE_MODEL, cfg.MODEL.END2END
  File "/home/hjq/I2R-NET/tools/../lib/models/transpose_h.py", line 700, in get_pose_net
    ckpt_state_dict = torch.load(pretrained_path, map_location=torch.device('cpu'))
  File "/home/hjq/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/hjq/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/hjq/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/base/transpose/tph_base_ochuman_256x192.pth'
i can 't find this file in models zoo.can you provide？

**Comment by leijue222** [comment]
It is not necessary to load the base model of the first stage in the test, I have modified the code, you can now try to run the test again.
The base models of TransPose and HRFormer on COCO are released in their official repositories. We will release the base models of CrowdPose and OCHuman as soon as possible.

**Comment by leijue222** [comment]
We have provide the complete models in [here](https://github.com/leijue222/Intra-and-Inter-Human-Relation-Network-for-MPEE#pretrained-models).
